"""
taxonomy.py — AI Agent Vulnerability Taxonomy
Aligned to OWASP Top 10 for Agentic Applications 2026 (ASI01–ASI10).

Every finding maps to one of the 10 ASI categories. Findings that fall
outside the current OWASP framework are reported under the BEYOND-ASI
prefix with a descriptive name generated by the scanner or AI layer.

Reference: OWASP Agentic Security Initiative (ASI) Top 10 — Dec 2025
"""

import json
import os
from typing import Any

_CONFIG_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "config")


def _load_json(filename: str) -> Any:
    with open(os.path.join(_CONFIG_DIR, filename), "r", encoding="utf-8") as f:
        return json.load(f)


AGENT_TAXONOMY: dict[str, dict[str, Any]] = _load_json("agent_taxonomy.json")

COMPLIANCE_MAPPINGS: dict[str, dict[str, list[str]]] = _load_json(
    "compliance_mappings.json"
)

BEYOND_ASI_SENTINEL = "BEYOND-ASI"

# Flat lookup: subcategory_key → full metadata (used by scorer.py)
FLAT_TAXONOMY: dict[str, dict[str, Any]] = {}
for _cat_key, _cat_data in AGENT_TAXONOMY.items():
    for _subcat_key, _subcat_data in _cat_data["subcategories"].items():
        FLAT_TAXONOMY[_subcat_key] = {
            "category": _cat_key,
            "asi_code": _cat_data["asi_code"],
            "asi_title": _cat_data["asi_title"],
            **_subcat_data,
        }


def get_finding_metadata(subcategory: str) -> dict[str, Any]:
    """Look up CVSS vector, severity, and ASI metadata for a subcategory."""
    return FLAT_TAXONOMY.get(
        subcategory,
        {
            "category": "beyond_asi",
            "asi_code": "BEYOND-ASI",
            "asi_title": "Beyond Current OWASP ASI Framework",
            "title": subcategory,
            "cvss_vector": "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N",
            "severity": "medium",
            "remediation": (
                "Review the finding and apply appropriate security controls "
                "based on the OWASP Agentic AI guidelines."
            ),
        },
    )


def get_compliance_mappings(subcategory: str) -> dict[str, list[str]]:
    """Return OWASP Agentic compliance mappings for a subcategory."""
    return COMPLIANCE_MAPPINGS.get(
        subcategory, {"owasp_agentic": [BEYOND_ASI_SENTINEL]}
    )


def is_owasp_classified(compliance_mappings: dict[str, list[str]]) -> bool:
    """Return True if at least one mapping starts with 'ASI'."""
    for entry in compliance_mappings.get("owasp_agentic", []):
        if entry.startswith("ASI"):
            return True
    return False
